### ISSUE TITLE
Sensor to Light Switch remapping

### ISSUE THREAD

**Issue by 350d** [merdok/homebridge-miot#535]
**Describe the idea or improvement**
[There is a clever solution](https://medium.com/jacob-tomlinson/using-xiaomi-door-window-sensors-as-light-switches-ce29d00aa981) available to use window/door sensor as smart light switch where some alias workaround needed to convert sensor to switch. Home Assistant example:

```
- alias: Light switch
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d000xxxxxc2
  action:
    service: light.toggle
    entity_id: light.somelight
```

**Describe the solution you'd like**
Is there any options already available to do that with this plugin or additional development needed?

**Additional context**
No context.
